spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mspayment
    username: postgres
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

client:
  ms-country:
    endpoint: http://localhost:8081